import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive Chinese-to-English translation mapping
const TRANSLATIONS: Record<string, string> = {
  // Navigation / Tabs
  '澄识': 'Clarity',
  '格物': 'Methodology',
  '进境': 'Progression',
  '记录': 'Journal',
  '主页': 'Home',
  '工具': 'Tools',
  '成长': 'Growth',
  '探索流派': 'Explore Schools',
  '探索工具': 'Explore Tools',
  '展开': 'Expand',
  '此刻，如何定义你的存在？': 'How do you define your existence right now?',
  
  // Dashboard & Mood Greetings
  '早上好，小明': 'Good morning, Ming',
  '中午好，小明': 'Good noon, Ming',
  '下午好，小明': 'Good afternoon, Ming',
  '晚上好，小明': 'Good evening, Ming',
  '你今天感觉如何?': 'How are you feeling today?',
  '很好': 'Great',
  '一般': 'Okay',
  '不好': 'Bad',
  '去记录': 'Go Log',
  '开始今日思辨记录': 'Start today\'s reflection',
  '哲学工具': 'Philosophy Tools',
  '查看全部': 'View All',
  '澄识指数': 'Clarity Index',
  '澄识指数计算公式': 'Clarity Index Formula',
  '什么是澄识指数？': 'What is the Clarity Index?',
  '澄识指数（Clarity Index, CI）是反映个体内在认知秩序、情绪解离水平与理性重构深度的量化指标。基于认知行为疗法（CBT）及经典哲学流派（斯多葛、儒家、实用主义等）的理论模型构建。': 'The Clarity Index (CI) is a quantitative index reflecting an individual\'s inner cognitive order, emotional dissociation, and depth of rational reconstruction. It is constructed based on cognitive behavioral therapy (CBT) and classical philosophical schools (Stoicism, Confucianism, Pragmatism, etc.).',
  '核心公式': 'Core Formula',
  '参数说明': 'Parameter Descriptions',
  '1. 认知重构系数 (Rr - Cognitive Reframing Factor)': '1. Cognitive Reframing Factor (Rr)',
  '衡量消极情绪或非理性信念被理性哲学框架（如斯多葛接受、儒家礼法克制、实用主义行动）成功重构的比例。**: 通过模型评估每个记录周期中的“秩序建立”质量。': 'Measures the proportion of negative emotions or irrational beliefs successfully reframed by rational philosophical frameworks (e.g., Stoic acceptance, Confucian self-discipline, Pragmatic action). Evaluates reflection quality for each period.',
  '2. 情绪解离深度 (Da - Affect Dissociation Depth)': '2. Affect Dissociation Depth (Da)',
  '评估用户在记录前后，初始情绪浓度与反思后澄明度之间的绝对差值。差值越大，说明情绪解离越彻底。**: $Da = \text{Initial Intensity} - \text{Post-reflection Intensity}$。': 'Evaluates the absolute difference between initial emotional intensity and post-reflection clarity. A larger difference indicates more thorough emotional dissociation: $Da = \text{Initial} - \text{Post}$.',
  '3. 认知秩序协同度 (Mc - Consistency & Order Synergy)': '3. Consistency & Order Synergy (Mc)',
  '反映连续记录的频率和思考的内在连贯性。避免情绪随外部事件过度摆动，从而建立稳定的决策和思考心流。**: 基于过去7天连续记录和思考的方差指数。': 'Reflects the frequency of continuous recording and the inner coherence of thinking to establish a stable flow of thought. Based on the 7-day streak and logging variance index.',
  '指数分级': 'Index Grading',
  '90-100 澄明 (Highly Clear)': '90-100 Highly Clear',
  '心物相通，理性重构高度自如，情绪能即时解离。': 'Mind and world are in harmony; rational reframing is effortless, and emotions dissociate instantly.',
  '70-89 渐悟 (Guided Clarity)': '70-89 Guided Clarity',
  '能够运用哲学工具解析日常，秩序感正在稳步建立。': 'Capable of analyzing daily life with philosophical tools; the sense of order is steadily building.',
  '50-69 混沌 (Struggling/Unordered)': '50-69 Struggling / Unordered',
  '情绪易受外在侵扰，理智与执念仍处于博弈拉扯阶段。': 'Emotions are easily disturbed by external factors; reason and attachment are still in conflict.',
  '0-49 执迷 (Distorted)': '0-49 Distorted',
  '缺乏认知工具，陷入单一情绪死循环，秩序亟待重建。': 'Lacking cognitive tools; trapped in emotional loops; order urgently needs to be reconstructed.',
  '全球平均': 'Global Average',
  '你的平均': 'Your Average',
  '所有徽章': 'All Badges',
  '你的徽章': 'Your Badges',
  '7天连续': '7-Day Streak',
  '反思大师': 'Reflection Master',
  '情绪记录者': 'Mood Log',
  '早期用户': 'Early User',
  '观察记录已保存': 'Observation saved',
  '请为你的心境选择一个出口': 'Please select an outlet for your state of mind',
  '当下的心境...': 'State of mind...',
  '快捷工具': 'Quick Tools',
  '消息中心': 'Message Center',
  '暂无新消息': 'No new messages',
  '全部已读': 'Mark all as read',
  '关闭': 'Close',
  '此刻的我们': 'Our Moment',
  '你今天的选择，也是这里的一盏灯。': 'Your choice today is also a light here.',
  '先写下今天的第一行，再回来看这扇窗。': 'Write today\'s first line first, and then come back to look at this window.',
  '今天有 X 人在澄识之径': 'Today, there are X people on the Clarity Path',
  '这里刚刚亮起第一盏灯。再过几天，会有更多人加入。': 'A single light has just been lit here. In a few days, more people will join.',
  '数据来自今天所有完成了记录的用户。明天醒来，这扇窗会刷新。': 'Data comes from all users who completed logs today. When you wake up tomorrow, this window will refresh.',
  '认知重构提醒': 'Cognitive Reconstruction',
  '在这个不确定的世界里，唯有你的认知边界能筑起笃定的港湾。': 'In this uncertain world, only your cognitive boundaries can build a secure harbor.',
  '静心思考时刻': 'Contemplation Moment',
  '外界纷扰皆是外在尘埃，回归当下的呼吸，建立你内在的秩序。': 'External disturbances are merely dust. Return to your breath now, and build your inner order.',
  '智能分析报告': 'Cognitive Update',
  '你已成功启动了“澄识之径”探索，继续前行，智慧将在记录中不断沉淀。': 'You have successfully embarked on the Path of Clarity. Keep documenting; wisdom is formed in reflection.',


  // Core Words
  '快乐': 'Joy',
  '喜悦与满足': 'Joy & satisfaction',
  '悲伤': 'Sadness',
  '忧愁与失落': 'Sorrow & loss',
  '愤怒': 'Anger',
  '不满与激动': 'Resentment & arousal',
  '爱情': 'Love',
  '浪漫与心动': 'Romance & affection',
  '孤独': 'Solitude',
  '独处与沉思': 'Solitude & contemplation',
  '自由': 'Freedom',
  '解脱与轻松': 'Liberation & ease',
  '亲情': 'Family',
  '温暖与牵挂': 'Warmth & care',
  '遗憾': 'Regret',
  '惋惜与反思': 'Regret & reflection',
  '焦虑': 'Anxiety',
  '担忧与不安': 'Worry & unease',
  '友情': 'Friendship',
  '陪伴与信任': 'Companionship & trust',

  // Schools list
  '斯多葛主义': 'Stoicism',
  '内在宁静': 'Inner Calm',
  '实用主义': 'Pragmatism',
  '行动真理': 'Action of Truth',
  '虚无主义': 'Nihilism',
  '存在无义': 'Absurd Existence',
  '儒家思想': 'Confucianism',
  '克己复礼': 'Self-Cultivation',

  // Step 2 & 3 Writing
  '哪种智慧能为你拨云见日？': 'Which wisdom can disperse the clouds for you?',
  '选择一种与你共鸣的视角': 'Select a perspective that resonates with you',
  '现在，你在想什么？': 'What is on your mind right now?',
  '澄的回响': 'Echo of Clarity',
  '保存现在': 'Save Present',
  '建立中...': 'Establishing...',
  '天气': 'Weather',
  '心情': 'Mood',
  '此刻天气': 'Current Weather',
  '情感温度': 'Emotional Temperature',
  '保存修改': 'Save Changes',
  '取消': 'Cancel',
  '思辨详情': 'Insight Details',
  '编辑内容': 'Edit Content',
  '删除日记': 'Delete Entry',
  '确定删除这篇日记吗？': 'Are you sure you want to delete this diary entry?',
  '删除后，对应的思辨足迹和心境状态将无法恢复。': 'Once deleted, corresponding contemplative traces and mood state cannot be recovered.',
  '确认删除': 'Confirm Delete',
  '智者回响': 'Sages\' Echo',
  '由于想象，我们承受的痛苦远多于由于现实。': 'We suffer more in imagination than in reality.',
  '伤害你的并非事物本身，而是你对事物的看法。': 'Suffer not from things themselves, but from your opinion of them.',
  '你有力量控制自己的心灵，而不是外界事件。认识到这一点，你就会找到真正的力量。': 'You have power over your mind - not outside events. Realize this, and you will find strength.',
  '改变你心中的世界，你就能改变外面客观的世界。': 'Change your thoughts and you change your world.',
  '人生的终极目的不是知识，而是从无尽的经验生长中发现并重建意义。': 'The great end of life is not knowledge but action.',
  '思想的唯一作用与终点，是让在不可知中颤栗的意志达成稳固的信念，从而恢复行动活力。': 'Belief is a rule of active habit, helping us recover our vigor to act.',
  '每一个不曾起舞的日子，都是对生命的辜负。': 'Every day we should consider lost on which we have not danced.',
  '若要存在，人必须自我选择。不选择同样是一种选择。': 'To exist is to choose. Not to choose is still a choice.',
  '深冬里，我终于领悟到，在我的内心深处，隐藏着一个不可战胜的夏天。': 'In the midst of winter, I found there was, within me, an invincible summer.',
  '仁者不忧，知者不惑，勇者不惧。': 'The wise are free from doubts, the virtuous from anxiety, and the brave from fear.',
  '万物皆备于我矣。反身而诚，乐莫大焉。': 'All things are complete within me. There is no greater joy than self-examination and truth.',
  '制天命而用之。': 'Control the decree of Heaven and put it to work.',
  '《沉思录》': 'Meditations',
  '《道德书简》': 'Letters from a Stoic',
  '《实用主义》': 'Pragmatism',
  '《民主与教育》': 'Democracy and Education',
  '《查拉图斯特拉如是说》': 'Thus Spoke Zarathustra',
  '《存在与虚无》': 'Being and Nothingness',
  '《论语》': 'The Analects',
  '《孟子》': 'Mencius',

  // Chronicles list
  '馆内暂无藏品': 'No reflective entries in archives yet',
  '当前分类下暂无思辨记录': 'No reflective logs under this filter',
  '最近足迹': 'Recent Footprints',
  '里程碑': 'Milestones',
  '所有流派': 'All Schools',
  '所有词汇': 'All Words',

  // Sages / Library View
  '先哲馆藏书架': 'Sages\' Archive Shelf',
  '主要思想先哲（点击深入研读）': 'Core Philosophical Sages (Click to study)',
  '收起 ✕': 'Collapse ✕',
  '古今日常叩问': 'Ancient & Modern Everyday Inquiries',
  '问': 'Q',
  '启': 'A',
  '经典思想内核': 'Core Philosophical Tenets',
  '推荐研读典籍': 'Recommended Readings',
  '心灵实践回响': 'Mental Echo Practice',
  '求索先哲折笺': 'Request Sages\' Letter',
  '结合你至今记录的思辨，为你亲启一封温润的书信手札。': 'Combining your reflections so far, unlock a warm hand-written letter.',
  '先哲笺信': 'Sages\' Letter',
  '重新祈问': 'Request Again',
  '学派的隔空对话': 'Dialog across Time',
  '亲启学派笺信': 'Open Sages\' Letter',
  '启信落墨中...': 'Ink is wet, opening...',
  '你的思辨修身足迹': 'Your Reflections Footprints',
  '在日记中尝试对该学派的观念进行实修后，足迹将记录于此': 'After practicing this school\'s concepts in journals, your footprints will appear here',

  // Profile status
  '秩序构建者': 'Order Constructor',
  '践行进度': 'Practice Progress',
  '总共记录了': 'Logged a total of',
  '次思想': 'thoughts',
  '在': 'with',
  '流派实践了': 'school practiced',
  '次': 'times',

  // Life Selector Tool (Steps & default dimensions)
  '返回历史决策列表': 'Back to decision history list',
  '确定要删除这条历史决策吗？': 'Are you sure you want to delete this decision?',
  '删除此条历史记录': 'Delete this record',
  '所有历史决策记录吗？清除后不可恢复。': 'All decisions history? This cannot be undone.',
  '清除全部档案': 'Clear all records',
  '最优理性推荐方案': 'Best rational recommendation',
  '其他分值': 'Other scores',
  '查看科学报告': 'View analysis report',
  '退出工具': 'Exit Tool',
  '当前决策流程': 'Current Decision',
  '历史决策': 'Decision History',
  '权重指南': 'Weight Guide',
  '评分指南': 'Scoring Guide',
  '你的难题是什么？': 'What is your core dilemma?',
  '例如：我现在该跳槽还是自己创业': 'e.g., Should I change jobs or start a business?',
  '用直白的一句话描述你当前最大的纠结。': 'Describe your biggest dilemma in one simple sentence.',
  '可以选择的路': 'Feasible options',
  '方案 ': 'Option ',
  '新方案': 'New Option',
  '方案 A': 'Option A',
  '方案 B': 'Option B',
  '方案A': 'Option A',
  '方案B': 'Option B',
  '移除此方案': 'Remove this option',
  '+ 添加新路径': '+ Add new path',
  '利弊发散': 'Brainstorming Pros & Cons',
  '问题：': 'Problem: ',
  '请尽可能多的列出每种方案的好处及坏处': 'List as many pros and cons as possible for each options',
  '+ 自定义评估维度': '+ Customize evaluation dimension',
  '关联评估维度': 'Map Evaluation Dimensions',
  '将刚才列出的好处与代价归纳到相应的价值维度中': 'Assign the pros and cons to relevant value domains',
  '分值量化与权重映射': 'Quantified Evaluation & Weight Mapping',
  '重新开始': 'Restart Decision',
  '上一步': 'Previous Step',
  '生成决策报告': 'Generate Report',
  '确认并继续': 'Next Step',
  '历史决策档案': 'Decision History Archives',
  '追溯与重新盘点过往人生路上的每一个关键命题': 'Trace and review every crossroad and dilemma in past years',
  '历史记录为空': 'No Decision Records Yet',
  '你还没有做过任何决策，完成一次建模即可在此查看历史分析日志。': 'Complete one decision matrix and you will see your history here.',
  '开始首次决策': 'Start First Decision',
  '明确问题': 'Define Dilemma',
  '界定核心难题': 'Define core issue',
  '列出方案': 'List Options',
  '探索可能路径': 'Explore ways',
  '定义评估维度': 'Define value domains',
  '将利弊归类': 'Sort pros & cons',
  '量化打分': 'Scoring Matrix',
  '权重与心理打分': 'Weight & scoring',
  '决策报告': 'Final Report',
  '理性分析结果': 'Rational summary',
  '金钱财富': 'Wealth & Finance',
  '自我实现': 'Self-Realization',
  '情感联结': 'Emotional Bonds',
  '物质基础、经济安全、资源自由': 'Financial foundation, security & liberty of resource',
  '成长、意义、成就感、成为想成为的人': 'Growth, meaning, achievement, being who you want to be',
  '亲情、友情、爱情，与他人真实地连接': 'Family, friendship, love, true connection with others',
  '价值建模': 'Value Modeling',
  '此刻，你的人生重心在哪里？': 'What is your current life dimension of focus?',
  '新维度': 'New Dimension',
  '移除': 'Remove',
  '权重': 'Weight',

  // Workplace Survival Tool
  '健康的适应': 'Healthy Adaptation',
  '危险的麻木': 'Dangerous Numbness',
  '中性观察': 'Neutral Observation',
  '职场生存研究': 'Workplace Survival Lab',
  '使用最多的策略': 'Most Used Strategy',
  '本月心态转变汇总': 'Mindset Shifts This Month',
  '研究主体 & 事件': 'Subjects & Events',
  '个研究对象': 'Subjects',
  '次事件': 'Events',
  '近期常遇标签 TOP 3': 'Frequent Stressor Tags TOP 3',
  '累计已探寻': 'Successfully Explored',
  '个自定义标签': 'Custom Tags',
  '建立第三人称系统视角，从观察、解构到应对的全流程职场记录系统。': 'A systematic record to build a third-person perspective: from observation to coping.',
  '添加观察对象': 'Add Subject',
  '研究员生存随笔': 'Researcher\'s Journal',
  '通过深度反思，重新整合个人立场与职业操守，不留未处理的情绪负荷过夜。': 'Reintegrate professional boundaries and emotional values through continuous reflections.',
  '职场日志分析中心': 'Workplace Logs Analysis',
  '通过动态归因分析和智者系统反馈，找到职场不适的结构性根源，变被动承受为主动解构。': 'Trace somatic stress to structural issues through dynamic correlation analysis.',
  '策略档案馆': 'Strategy Archives',
  '深度学习经典心理防御、边界保护、预期管理和系统思维分析，沉淀你量身定制的求生手册。': 'Study psychological coping, boundary protection, and systemic reasoning.',
  '高级研究员自定义标签库': 'Custom Stressor Tags Library',
  '对组织中那些令你应激的隐性不妥进行学术化命名。': 'Name the invisible stress and organizational dysfunctions around you academically.',
  '退出职场研究': 'Exit Workplace Survival',
  '职场生存观察': 'Workplace Survival Lab',
  '日志历史': 'Logs History',
  '新增记录': 'New Reflection Log',
  '归因分析': 'Correlation Matrix',
  '随笔手札': 'Essays & Notes',
  '自定义标签': 'Stressor Tags',
  '策略手册': 'Coping Strategies',

  // Sages detail block translation
  '塞内卡 (Seneca)': 'Seneca',
  '爱比克泰德 (Epictetus)': 'Epictetus',
  '马可·奥勒留 (Marcus Aurelius)': 'Marcus Aurelius',
  '威廉·詹姆斯 (William James)': 'William James',
  '约翰·杜威 (John Dewey)': 'John Dewey',
  '查尔斯·皮尔士 (Charles Peirce)': 'Charles Peirce',
  '弗里德里希·尼采 (Friedrich Nietzsche)': 'Friedrich Nietzsche',
  '让-保罗·萨特 (Jean-Paul Sartre)': 'Jean-Paul Sartre',
  '阿尔贝·加缪 (Albert Camus)': 'Albert Camus',
  '孔子 (Confucius)': 'Confucius',
  '孟子 (Mencius)': 'Mencius',
  '荀子 (Xunzi)': 'Xunzi',

  // Survival Categories
  '沟通与信息障碍': 'Communication Barriers',
  '决策与逻辑失序': 'Decision & Logic Disorders',
  '人际与态度': 'Interpersonal & Attitude',
  '管理能力缺失': 'Management Lack',
  '职业操守与情绪': 'Professional Integrity & Emotions',
  '生理信号标签': 'Physiological Signals',
  '即时行动标签': 'Immediate Action Tags',

  // Survival Tags
  '指令模糊': 'Vague Instruction',
  '任务目标、标准或期限不明确。': 'Task objectives, standards, or deadlines are unclear.',
  '信息反复': 'Repeated Info Shifts',
  '对同一事务的指示在短时间内无理由变更。': 'Instructions on the same matter are changed for no apparent reason in a short time.',
  '渠道错位': 'Channel Misalignment',
  '在重要事务上拒绝使用可留痕的正式渠道。': 'Refusal to use official traceable channels for important matters.',
  '沟通垄断': 'Communication Monopoly',
  '讨论中垄断发言权，打断或否定他人。': 'Monopolizing speech in discussions, interrupting or dismissing others.',
  '决策摇摆': 'Decision Swaying',
  '重要决策上长期犹豫或随意更改。': 'Hesitating for a long time or changing important decisions at will.',
  '优先级冲突': 'Priority Conflict',
  '同时下达多个紧急任务且无合理排序。': 'Issuing multiple urgent tasks at once with no reasonable sequencing.',
  '归咎于人': 'Blame Placement',
  '问题出现时，第一反应是寻找并指责责任人。': 'The first response when an issue arises is to find and blame someone.',
  '逻辑断裂': 'Broken Logic',
  '给出的理由明显不符合常识、数据或流程。': 'The reasons given obviously do not conform to common sense, data, or processes.',
  '公开贬低': 'Public Disparagement',
  '在他人面前对个人能力或性格进行贬损。': 'Belittling personal ability or character in front of others.',
  '差别对待': 'Differential Treatment',
  '在任务分配、资源支持上无合理依据的亲疏之别。': 'No reasonable basis for task allocation or support based on personal closeness.',
  '功功占有': 'Credit Takeover', // Typo buffer
  '功劳占有': 'Credit Takeover',
  '将团队或下属成果主要归功于自己。': 'Attributing team or subordinate achievements mainly to oneself.',
  '过度窥探': 'Over-Inquiry',
  '过度干涉与工作绩效无直接关系的个人事务。': 'Excessive interference in personal matters with no direct relation to performance.',
  '屏蔽信息': 'Info Blocking',
  '阻断向上或横向的关键信息流通。': 'Blocking the flow of critical information upward or sideways.',
  '资源悬空': 'Resource Suspension',
  '下达任务时，未能提供必要的权限、预算或时间。': 'Failing to provide necessary authority, budget, or time when assigning tasks.',
  '保护失能': 'Buffer Failure',
  '团队遭遇外部不公时，未能履行管理者的缓冲职责。': 'Failing to perform the buffer role of a manager when the team faces external unfairness.',
  '发展漠视': 'Development Neglect',
  '对下属的职业成长表现出持续的不支持。': 'Showing persistent lack of support for subordinate career growth.',
  '边界侵犯': 'Boundary Intrusion',
  '要求下属从事明显超出合理工作范围的事务。': 'Demanding subordinates handle matters clearly outside the reasonable scope of work.',
  '情绪宣泄': 'Emotional Venting',
  '将个人愤怒、焦虑等情绪在工作场合不加控制地释放。': 'Uncontrolled release of personal anger, anxiety, or other emotions in the workplace.',
  '规则双标': 'Double Standards',
  '对自己和下属执行两套不同的规则。': 'Executing two different sets of rules for oneself and subordinates.',
  '诚信疑虑': 'Integrity Doubts',
  '在关键信息上可能出现故意隐瞒或扭曲事实的行为。': 'Deliberate concealment of key information or distortion of facts.',
  '恶心': 'Nausea',
  '感觉胃部不适，恶心欲吐或反胃。': 'Feeling stomach discomfort, nausea, or heartburn.',
  '头晕': 'Dizziness',
  '感到头部眩晕，身体重心不稳或太阳穴发胀。': 'Feeling dizzy, unstable, or having throbbing temples.',
  '胃部紧绷': 'Tight Stomach',
  '胃部有紧张 or 痉挛感。': 'Tension or spasms in the stomach.',
  '心跳加速': 'Rapid Heartbeat',
  '明显感觉到心跳加快，呼吸急促。': 'Noticeable acceleration of heart rate and short, rapid breaths.',
  '肩颈僵硬': 'Stiff Shoulders',
  '双肩和颈部感到酸胀、紧绷。': 'Shoulders and neck feeling sore and tight.',
  '呼吸浅快': 'Shallow Breaths',
  '呼吸频率加快但深度变浅。': 'Increased breathing rate but shallow depth.',
  '头痛/眩晕': 'Headache/Dizziness',
  '感到头部发紧或有轻微眩晕感。': 'Feeling tightness in the head or slight dizziness.',
  '手心出汗': 'Sweaty Palms',
  '手掌心发热并有细微出汗现象。': 'Palms feeling warm and slightly sweaty.',
  '无异常': 'Normal',
  '身体无明显的应激生理指标反应。': 'No obvious physiological stress responses.',
  '沉默': 'Silence',
  '不进行语言反驳，保持静默。': 'Not verbally refuting, keeping quiet.',
  '解释': 'Explanation',
  '试图通过详细解释来证明自己的立场。': 'Attempting to prove one\'s stance through detailed explanations.',
  '按指示做': 'Obey Instructions',
  '顺从对方要求，保留异议并执行。': 'Complying with requests, executing while reserving differences.',
  '结构化确认法': 'Structured Confirmation',
  '使用复述和确认等结构化沟通澄清指令。': 'Using structured communication like repeating and confirming to clarify instructions.',
  '延迟回复': 'Delayed Response',
  '推迟响应时间，避免即时情绪化反馈。': 'Delaying response time to avoid immediate emotional feedback.',
  '寻求第三方支持': 'Seek Third-Party Support',
  '联系同事、HR或外部专业人士获取建议和帮助。': 'Contacting colleagues, HR, or external professionals for advice.',
  '记录证据': 'Log Evidence',
  '通过文字、邮件或截图保存当期事实证据。': 'Saving factual evidence through text, emails, or screenshots.',

  // Survival Strategies
  '去人格化解读': 'Depersonalization Stance',
  '系统思维分析': 'Systemic Thinking',
  '边界重建': 'Boundary Rebuilding',
  '成本收益核算': 'Cost-Benefit Assessment',
  '预期管理': 'Expectation Management',
  '认知重构': 'Cognitive Reframing',
  '情感隔离': 'Emotional Isolation',
  '将对方的不合理行为，理解为其自身困境、焦虑或能力不足的表现，而非对你个人价值的否定。': 'Understand unreasonable actions as expressions of the other\'s anxiety or deficits, rather than denial of your value.',
  '不孤立看待一个人或一件事，而是将其放在更大的组织系统、权力结构和利益链条中理解。': 'Never view an event in isolation; contextualize it within organizational structure and power networks.',
  '在情绪和职责上，明确区分什么是“我的事情”，什么是“别人的事情”，保护自己的心理空间不被入侵。': 'Differentiate between "my responsibility" and "others\' business" emotionally to guard your mental sanctuary.',
  '将情绪消耗、时间损耗也视为“成本”，用理性计算代替感性纠结。': 'Treat emotional depletion and time loss as cost coordinates, computing returns on energy investment rationally.',
  '主动调整自己对他人、对自己、对结果的期望值，让期望与现实之间的落差变小，从而减少失望和痛苦。': 'Calibrate expectation parameters for others, self, and outcomes to narrow the delta of disappointment.',
  '改变你对一件事的“解释框架”，从而改变你的情绪反应。事情本身不变，但你看它的角度变了。': 'Reframe explanatory structures of happenings to alter emotional outcomes: events stay constant, perspectives shift.',
  '在特定情境下，暂时将自己的感受“搁置”起来，以完成任务为目标，事后再处理情绪。': 'Temporarily shelve emotional affects during stress to execute tasks efficiently, processing feelings afterward.',

  // General buttons / fallbacks
  '返回': 'Back',
  '保存': 'Save',
  '提交': 'Submit',
  '删除': 'Delete',
  '进入澄识之径': 'Enter Clarity Pathway',
  '开启探索': 'Start Journey',
  '下一步': 'Next Step',
  '上一步': 'Previous Step',
  '恭喜解锁勋衔': 'Congratulations! Badge Unlocked',
  '破晓行者': 'Dawnwalker',
  '完成第1篇哲学日记': 'Complete 1st philosophical journal',
  '深度思辨': 'Deep Speculator',
  '累计5篇哲学日记': 'Log a total of 5 journal entries',
  '秩序守护': 'Guardian of Order',
  '探索过3个哲学流派': 'Explore 3 philosophical schools',
  '格物大师': 'Method Master',
  '常用工具辅助思考': 'Log 10 entries using mental tools',

  // 8 Milestones / Badges & Settings UI
  '我的里程碑': 'My Milestones',
  '成果展示设置': 'Display Showcase Settings',
  '自主选择 1 到 4 个已解锁或心仪的成就展示于成长主页': 'Select 1 to 4 unlocked or favorite milestones to display on Growth Home',
  '请选择最多 4 个里程碑展示（至少 1 个）': 'Please select 1 to 4 milestones to display (at least 1)',
  '已选': 'Selected',
  '个': 'items',
  '设为展示': 'Display',
  '取消展示': 'Cancel Display',
  '展示中': 'Showcased',
  '理性先锋': 'Rational Pioneer',
  '评估生命决策利弊 1 次': 'Evaluate decision matrix 1 time',
  '成长之萌': 'Sprouting Insight',
  '累计打卡 3 次哲学日记': 'Log a total of 3 journal entries',
  '累计撰写 5 篇哲学日记': 'Log a total of 5 journal entries',
  '见微知著': 'Keen Perceiver',
  '累计进行 8 次心情探究': 'Log a total of 8 journal entries',
  '格物大成': 'Mastery of Method',
  '累计撰写 10 篇哲学日记': 'Log a total of 10 journal entries',
  '思维重构': 'Cognitive Restructuring',
  '解锁且探索过 3 个流派': 'Explore 3 philosophical schools',
  '见字如面': 'Sincere Expression',
  '随笔字数超过 100 字 1 次': 'Write an entry with over 100 characters',
  '未解锁': 'Locked',
  '已解锁': 'Unlocked',

  // Sages extra
  '塞内卡': 'Seneca',
  '爱比克泰德': 'Epictetus',
  '马可·奥勒留': 'Marcus Aurelius',
  '威廉·詹姆斯': 'William James',
  '约翰·杜威': 'John Dewey',
  '查尔斯·皮尔士': 'Charles Peirce',
  '弗里德里希·尼采': 'Friedrich Nietzsche',
  '让-保罗·萨特': 'Jean-Paul Sartre',
  '阿尔贝·加缪': 'Albert Camus',
  '孔子': 'Confucius',
  '孟子': 'Mencius',
  '荀子': 'Xunzi',

  // Newly Added Translations (Decision Matrix/Life Selector & Workplace Survival)
  '人生选择器': 'Rational Decision Analysis Table',
  '理性决策分析表': 'Rational Decision Analysis Table',
  '量化利弊，破除决策迷雾': 'Quantify pros & cons, dissolve decision fog',
  '理论模型支持': 'Theoretical Model Support',
  '多属性效用理论 (Multi-Attribute Utility Theory, MAUT)': 'Multi-Attribute Utility Theory (MAUT)',
  '本工具基于决策科学中的': 'This tool is based on ',
  '。通过将复杂的决策命题拆解为具体的“价值维度”（属性）并分配“主观权重”，结合对各个利弊的客观测度，用数学加权的方法算出整体决策效用。这是一种公认具有深度科学依据的理性决策模型。': ' in decision-making science. By decomposing complex decision problems into concrete "value dimensions" (attributes) and assigning "subjective weights", combined with objective measurement of pros and cons, it calculates the overall decision utility through mathematical weighting. This is a universally recognized rational decision-making model with deep scientific backing.',
  '量化利弊破，除决策迷雾': 'Quantify pros & cons, dissolve decision fog',
  '量化利弊破除决策迷雾': 'Quantify pros & cons, dissolve decision fog',
  '解构互动，沉淀职场法则': 'Deconstruct interactions, crystallize workplace rules',
  '更多工具，敬请期待': 'More Tools Coming Soon',
  '更多工具敬请期待': 'More Tools Coming Soon',
  '探索更多思维解离与重构工具': 'Explore more tools for cognitive reconstruction',
  '未决': 'Undecided',
  '删除记录': 'Delete Record',
  '确定要清空所有历史决策记录吗？清除后不可恢复。': 'Are you sure you want to clear all history records? This cannot be undone.',
  '的量化评估': 'Quantitative Evaluation',
  '当前加权净分': 'Weighted Net Score',
  '收益打分 (0-100)': 'Gain Score (0-100)',
  '代价打分 (0-100)': 'Cost Score (0-100)',
  '未填写描述': 'No description provided',
  '归属于:': 'Assigned to:',
  '-- 请选择评估维度 --': '-- Please select an evaluation dimension --',
  '将收获关联至维度': 'Map gains to dimensions',
  '将代价关联至维度': 'Map costs to dimensions',
  '最优理性路径推荐': 'Best Rational Path Recommendation',
  '综合决策分值:': 'Overall Decision Score:',
  '价值分布图': 'Value Distribution Map',
  '展示': 'Display',
  '在各维度的净收益表现': 'net benefits across all dimensions',
  '净收益': 'Net Benefits',
  '维度影响力分解': 'Dimension Influence Breakdown',
  '哪些价值观决定了这个结果？': 'Which values determined this outcome?',
  '影响点': 'impact points',
  '所有方案对比排位': 'All Options Comparison & Ranking',
  '理性的选择不是寻找完美，而是在所有不完美的路径中，找到最符合你当下价值观的那一条。': 'Rational choice is not about seeking perfection, but about finding the path that best aligns with your current values among all imperfect paths.',
  '这个报告基于你对': 'This report is based on your weight configuration for',
  '个价值维度': 'value dimensions',
  '的权重定义。如果结果令你惊讶，请回到': '. If the results surprise you, please return to the',
  '步骤审视权重。': 'step to review your weights.',
  '权重设定指南': 'Weight Setting Guide',
  '权重逻辑定义': 'Weight Logic Definition',
  '权重描述手册': 'Weight Description Handbook',
  '评分指南': 'Scoring Guidelines',
  '打分逻辑定义': 'Scoring Logic Definition',
  '核心评估原理': 'Core Evaluation Principles',
  '没有“一票否决”': 'No "One-Vote Veto"',
  '任何单一因素都不应直接决定最终选择。理性在于全面权衡，通过分值反映每一个维度的真实分量。': 'No single factor should directly determine the final choice. Rationality lies in comprehensive trade-offs, reflecting the weight of each dimension.',
  '分数代表“重量”': 'Scores represent "Weight"',
  '高分意味着你非常在意这件事。打分是主观价值的客观量化，是寻找内心真正优先级的过程。': 'High scores mean you care a lot. Scoring is the objective quantification of subjective values, a process of finding your inner priorities.',
  '分值区间定义': 'Score Range Definitions',
  '好处定义': 'Pros Definition',
  '坏处定义': 'Cons Definition',
  '无力': 'Powerless',
  '可笑': 'Ridiculous',
  '平静': 'Calm',
  '委屈': 'Aggrieved',
  '震惊': 'Shocked',
  '基于更清醒的认知，节省了无谓的情绪消耗。': 'Based on clearer awareness, saving needless emotional exhaustion.',
  '源于放弃挣扎，开始接受不合理为“常态”。': 'Stemming from giving up struggle, beginning to accept unreasonableness as "normal".',
  '只是一种暂时状态，有待观察。': 'Only a temporary state, yet to be observed.',
  '研究员行为守则': 'Researcher Code of Conduct',
  '观察者不审判': 'Observation without Judgement',
  '记录事实而非评判对错，你的目标不是给谁定罪。': 'Record facts rather than judge right or wrong, your goal is not to condemn anyone.',
  '解构即释能': 'Deconstruction is Empowerment',
  '看穿现象的运行逻辑，压迫便自行松绑。': 'See through the underlying logic of phenomena, and the oppression will unbind itself.',
  '研究是为了行动': 'Research for Action',
  '日志的终点不是情绪宣泄，而是提炼出属于你的生存法则。': 'The ultimate goal of journaling is not venting, but crystallising your own survival rules.',
  '思考中...': 'Thinking...',
  '✨ AI 辅助深度分析': '✨ AI-Assisted Deep Analysis',
  '获得/好处': 'Gains / Pros',
  '代价/坏处': 'Costs / Cons',
  '移除': 'Remove',
  '+ 新增': '+ Add New',
  '输入好处描述...': 'Describe some pros...',
  '输入坏处描述...': 'Describe some cons...',
  '微弱': 'Weak',
  '中等偏低': 'Moderate-Low',
  '中等': 'Moderate',
  '强烈': 'Strong',
  '极强': 'Very Strong',
  '有点小好处，几乎不影响决定': 'Slight benefits, barely affects decision',
  '有点小麻烦，几乎不影响决定': 'Slight troubles, barely affects decision',
  '能感觉到好处，是考虑因素之一': 'Perceivable benefits, one of the factors considered',
  '能感觉到不适，是考虑因素之一': 'Perceivable discomfort, one of the factors considered',
  '明确的好处，我会认真权衡它': 'Clear benefits, I will weigh it seriously',
  '明确的坏处，我会认真权衡它': 'Clear cons, I will weigh it seriously',
  '有吸引力的好处，很舍不得放弃': 'Attractive benefits, reluctant to give up',
  '难以忍受的坏处，会很抗拒接受': 'Intolerable cons, strongly reluctant to accept',
  '极其看重，有巨大的吸引力': 'Extremely valued, great attraction',
  '极其厌恶，对我是巨大的阻力': 'Extremely loathed, major resistance',
  '自动弹出指引': 'Auto-Popup Guide',
  '在决策流程中的打分步骤自动弹出此指南': 'Automatically show this handbook in the scoring phase.',
  '在决策流程中的建模步骤自动弹出此指南': 'Automatically show this handbook in the modeling phase.',
  '核心设定原则': 'Core Setting Principles',
  '描绘“现在的我”': 'Portray "Who I Am Now"',
  '权重代表你当前生活的真实重心，没有对错之分。诚实地勾选“现在的我”，比纠结“应该怎样”更重要。': 'Weight represents the actual center of gravity of your life right now, there is no right or wrong. Being honest about yourself is more important than worrying over what "should" be.',
  '级权重': 'Level Weight',
  '不太在意': 'Slight Care',
  '缺点在乎': 'Slight Concern',
  '优点在乎': 'Slight Concern',
  '有点在乎': 'Somewhat Concerned',
  '正常在乎': 'Normally Concerned',
  '很在乎': 'Highly Concerned',
  '极其在乎': 'Extremely Concerned',
  '这个维度基本不会影响我的选择。它不是我的重心，我也不会因为它而纠结。': 'This dimension will barely affect my choice. It is not my focus, nor will I deliberate on it.',
  '我会考虑到它，但它不是主角。如果其他方面足够好，我可以接受它不完美。': 'I will consider it, but it is not the main player. If other aspects are good enough, I can accept its imperfection.',
  '我会认真对待它，和大多数人一样。它是我放在天平上一起称量的因素之一。': 'I will take it seriously, like most people. It is one of the factors weighed together on the scale.',
  '这对我很重要，不能满足我会很犹豫。它是我做出好选择的关键拼图之一。': 'This is very important to me; I would hesitate if unsatisfied. It is a critical puzzle piece for a good choice.',
  '这个维度定义了我想要的生活方向。我会优先追求它，投入最大的精力。': 'This dimension defines the direction of life I seek. I will prioritize it and invest my utmost energy.',
  '添加观察对象': 'Add Research Subject',
  '研究状态': 'Research Status',
  '化名 / 对象代号': 'Alias / Code Name',
  '角色 / 岗位职级': 'Role / Job Position',
  '背景脉络与互动简述': 'Background & Brief Interaction Context',
  '研究状态说明': 'Research Status Description',
  '🟢 观察研究中': '🟢 Under Study',
  '⚫ 已完成研究': '⚫ Completed Study',
  '🟢 观察研究中 :': '🟢 Under Study:',
  '⚫ 已完成研究 :': '⚫ Completed Study:',
  '对象为活跃观察状态。项目内可正常为其录入工作日志，并在研究员随笔处录入心流笔录。': 'The subject is active under study. Job logs can be normally entered, and researcher essays/reflective notes can be added.',
  '研究已完成或归档。该对象将自动在新增日志、研究员随笔的选择器中隐藏，帮助你聚焦于进行中的研究。如需重新激活，请将其设回「观察研究中」。': 'The research is archived or completed. The subject is auto-hidden from selections for new logs or essays to keep active research clean. Re-toggle active anytime.',
  '编辑研究对象信息': 'Edit Research Subject Info',
  '观察研究对象 (Research Subject)': 'Research Subject',
  '观察到的职场事实 (Fact Details)': 'Observed Workplace Facts',
  '应激与反应指标': 'Stress & Response Indicators',
  '情绪反应烈度 (1-10级)': 'Emotional Response Intensity (Level 1-10)',
  '生理信号记录 (Physical Signals)': 'Physiological Signals Log',
  '即时采取行动 (Immediate Action)': 'Immediate Action Taken',
  '请选择即时应对': 'Please select immediate coping',
  '认知转变与解构心态策略': 'Cognitive Shift & Deconstruction Stance',
  '理性概念转变/转折念头 (Pivot Thought)': 'Pivot Thought / Rational Concept Shift',
  '那句能拉开情绪距离，使你重获理性的关键念头...': 'That critical thought that pulls you back to restore rationality...',
  '启用的解构心态策略 (Select Strategies)': 'Selected Coping Strategies',
  '定位与生存法则是守': 'State Tags and Survival Rules',
  '定位心态标签 (State Tag)': 'State Stance Tags',
  '例如: 冷眼看剧、防御启动': 'e.g., Detached onlooker, Defense mode active',
  '自评安全水位': 'Self-Assessment Safety Level',
  '沉淀的职场核心生存法则 (Survival Rule)': 'Crystallised Workplace Survival Rules',
  '例如：警惕任何情绪溢价...': 'e.g., Beware of any emotional premium...',
  '附加观察笔记/随笔随想': 'Additional Notes / Essays',
  '有何细节可补充...': 'Any further supporting details...',
  '标签归纳 (Associated Tags)': 'Associated Stressor/Action Tags',
  '取消修改': 'Cancel',
  '保存修改并存档': 'Save Changes and Archive',
  '修改此篇观察存档的所有事实与心态解构评估指标': 'Update all fact logs and mental deconstruction indicators for this record.',
  '二次编辑观察研究记录': 'Edit Observation & Research Log',
  '退出的工具': 'Exit Tool',
  '功能分类': 'Functional Classification',
  '观察时间:': 'Observation Time:',
  '研究对象:': 'Research Subject:',
  '二次编辑': 'Edit Record',
  '删除报告': 'Delete Report',
  '01. 事实记录与行为分类': '01. Facts and Behavioral Categories',
  '[ 事实记录 ]': '[ Factual records ]',
  '[ 行为分类 ]': '[ Behavior tags ]',
  '02. 第一时间反应': '02. Immediate Somatic Reactions',
  '[ 情绪反应 ]': '[ Emotional response ]',
  '未检出明显的异常情绪极化反应': 'No significant emotional polarization detected',
  '[ 生理信号 ]': '[ Physiological response ]',
  '躯体植物神经机制运转平稳': 'Somatic vegetative systems running stable',
  '[ 即时反应 ]': '[ Immediate action ]',
  '03. 认知催化与演变': '03. Cognitive Evolution',
  '[ 演变转折点 ]': '[ Turning Point ]',
  '未检测到明显的非理性偏见重构或逆转节点': 'No Irrational bias re-framing or turn-around detected',
  '[ 运用的深度解构策略 ]': '[ Coping strategy used ]',
  '在思维演化中未选用特定预设心态策略体系': 'No specific psychological coping strategy selected',
  '04. 生存法则与防同化自测': '04. Survival Laws & Anti-Assimilation',
  '[ 生存法则 ]': '[ Survival Rule ]',
  '在本次经历中未写明安全生存守则': 'No survival rule recorded for this experience.',
  '[ 防同化自测 ]': '[ Anti-Assimilation ]',
  '05. 辩证追问与自省': '05. Dialectical Inquiry & Reflection',
  '关闭报告': 'Close Report',
  '关闭 modal': 'Close Modal',
  '强度：': 'Intensity: ',
  '没有一票否决': 'No "One-Vote Veto"',
  '分数代表重量': 'Scores represent "Weight"',
  
  // Custom Workplace & Growth and Life Selector translations
  '日记档案馆': 'Diary Archive',
  '撰写思辨感悟': 'Write Speculative Reflection',
  '在这里记录你的哲思与顿悟...': 'Log your philosophy & epiphanies here...',
  '出处与解读': 'Source & Interpretation',
  '引自：': 'Cited from: ',
  '先贤古代典籍': 'Ancient Classics',
  '引借古今先贤之崇高哲思，用以正己省身、涵养理性，平息凡闹日常之侵染。': 'Borrow the noble philosophy of ancient and modern sages to reflect on oneself and nurture reason, calming the invasion of daily trivialities.',
  '山河辽阔，墨笔暂竭。请稍后再试，与睿智意志重连。': 'The mountains and rivers are vast, and the ink is temporarily dry. Please try again later to reconnect with the wise will.',
  '书房': 'Study',
  '作者：': 'Author: ',
  '个已记录维度': 'explored dimensions',
  '“心智之秩序不应任凭本能摆弄，而应交由先贤理性所铸之框架安放。在此翻阅学派书室，让每一次日常实践都在古典智慧中交汇。”': 'The order of the mind should not be left to the mercy of instinct, but should be placed in the framework forged by the reason of the sages. Read the school rooms here, and let every daily practice build an intersection with classical wisdom.',
  '已探寻': 'Discovered',
  '未涉及': 'Not Explored',
  '实践足迹': 'Reflections Count',
  '篇': 'entries',
  '尚无涉猎历史': 'No study history yet',
  '研读': 'Study',
  '进入': 'Enter',
  '当你面临两个（或更多）选项，反复纠结、无法下定决心时，试试这个工具。': 'When you are faced with two (or more) options, hesitate repeatedly, and cannot make up your mind, try this tool.',
  '它不适合“一拍脑门就能决定”的小事，也不适合“完全没想法”的迷茫。它最擅长的是：你心里已有几个模糊的方向，但总在选项之间来回拉扯，越想越乱。': 'It is not suitable for small things that can be decided in a snap of the fingers, nor for confusion with "no ideas." It is best at: you have a few vague directions in mind, but always pull back and forth between options.',
  '你只需要': 'You only need to',
  '诚实地写下每个选项的好处与坏处': 'Honestly write down the pros & cons of each option',
  '只聚焦当前这一项。': 'Focus only on the current one.',
  '设定你当下最在乎的几个维度的权重': 'Set weights of dimensions you care about most right now',
  '按你的生活重心分配数字。': 'Distribute numbers according to your focus of life.',
  '给每个利弊打分': 'Score each pro & con',
  '凭感觉打分，系统会综合计算。': 'Score by intuition, the system computes synthetically.',
  '系统会帮你将“内心的天平”可视化，计算出整体倾向。这并非替你做决定，而是让你看清自己更倾斜于哪一方、原来自己比想象中更在意某件事。': 'The system helps you visualize "the scale of your heart" and calculate overall leaning. This does not make decisions for you; it lets you see clearly which side you lean toward, and that you care about something more than you thought.',
  '每一次量化，都是一次更清晰的自我澄明。': 'Every quantification is a clearer path to self-clarification.',
  '决策数据档案': 'Decision Archives',
  '最近一月决策': 'Decisions in Past Month',
  '最看重维度': 'Top Dimension',
  '最近一次决策命题': 'Latest Decision Topic',
  '尚未开启首个决策命题': 'Not started yet',
  '内在核心关注点演化趋势 (限最近8次)': 'Evolution of Core Concerns (last 8 times)',
  '🍁 完成 2 次决策后': '🍁 After completing 2 decisions',
  '系统将自动绘制“内在天平维度权重”的变化趋势图': 'The system will automatically draw the trend of dimensional weights.',
  '当你身处不舒服的环境，却因为种种客观原因暂时无法离开时，试试这个工具。': 'When you are in an uncomfortable environment but cannot leave temporarily due to objective reasons, try this tool.',
  '它不是教你“隐忍妥协”，也不是鼓励你“意气离职”。它是一套帮你实现角色转换的认知框架，帮助你从局中人的“负面消耗”切换到极度客观的“观察研究”。': 'It does not teach "resignation and compromise", nor "impulsive quitting". It is a cognitive framework to change roles, shifting from deep personal drain to highly objective observation and research.',
  '如实记录发生了什么': 'Record what happened truthfully',
  '像旁观者一样写下事实，不加评判。': 'Write down facts like an onlooker, without judgment.',
  '标记那些让你难受的行为': 'Tag behavior that bothers you',
  '从标签库里选一个，看清困扰你的模式。': 'Choose one from tag database, see the pattern troubling you.',
  '跟随引导，拆解自己的情绪': 'Follow the guidance to dismantle your emotions',
  '尝试不同的认知策略，让情绪慢慢松绑。': 'Try different cognitive strategies to ease emotional pressure.',
  '你会发现，情绪依然真实，但它的虚耗感正逐渐松绑。你不是在忍受折磨，而是在研究这个环境、剖析 these 现象，同时更好地了解自身的心理机制。': 'You will find emotions still real, but draining feeling slowly loosens up. You are not enduring torture; you are studying this environment, dissecting phenomena, and understanding your psychological habits better.',
  '若注定终将离开，必定带走最清醒的认知；若仍需前行，轻装上阵。': 'If parting is inevitable, walk away with the clearest insights; if keeping on is required, carry less baggage.',
  '职场生存研究数据': 'Workplace Survival Data',
  '尚未标记高频应激行为': 'No high-frequency stress behaviors tagged yet',
  '暂未使用策略': 'No strategy used yet',
  '次使用': 'times used',
  '篇思辨日记': ' speculative logs',
  '思辨偏好分布': 'Speculation Preference Profile',
  '暂无足迹，开启你的第一次构建': 'No footprints yet. Begin your first construction',
  '01. 基础事实与研究对象': '01. Underlyings & Subjects',
  '02. 应激与反应指标': '02. Somatic stress & response indices',
  '03. 认知转变与解构心态策略': '03. Pivot thought & deconstruct strategy',
  '数据不足以支撑模式识别': 'Insufficient data to trigger pattern recognition',
  '请积累至少 3 篇观察日志后再启动周期深度分析。': 'Please accumulate at least 3 observation logs before starting cyclical deep analysis.',
  '无': 'None',
  '已完成': 'Completed',
  '级': 'Level ',
  'L3': 'L3',
  'L6': 'L6',
  'L9': 'L9',

  // Additional missing Workplace Survival translations
  '实验室': 'Lab',
  '新记录': 'New Log',
  '观察日志': 'Observation Logs',
  '实验室准备中...': 'Lab is preparing...',
  '开始记录前，请先在“研究对象”菜单中定义一个你正在观察的目标人物。': 'Before recording, please define a subject under observation in the "Subjects" menu.',
  '立即去创建研究对象': 'Create Research Subject Now',
  '研究员随笔': 'Researcher\'s Journal',
  '研究对象管理': 'Subjects Admin',
  '周期洞察': 'Cyclic Insights',
  '标签库': 'Tags Library',
  '策略库': 'Strategies Library',
  '已创建的研究对象': 'Created Research Subjects',
  '尚未建立任何观察研究对象': 'No research subjects established yet.',
  '研究中': 'Under Study',
  '暂无详细背景记录。': 'No detailed background recorded yet.',
  '点击查看': 'Click to view',
  '篇日志': 'logs',
  '新增研究对象': 'New Subject',
  '定制并录入新的观察研究对象': 'Customize and Input New Research Subject',
  '收起': 'Collapse',
  '例如：对象A、神秘上司': 'e.g., Subject A, Mysterious Boss',
  '例如：直属领导、产品经理、合作方': 'e.g., Direct Supervisor, Product Manager, Partner',
  '补充其背书背景，或在职场中对该对象的观察脉络...': 'Add background check or interaction context on this subject...',
  '录入并开始观察研究': 'Submit and Start Observation',
  '退出工具': 'Exit Tool',
  '已完成研究': 'Completed Study',
  '观察研究中': 'Under Study',
  '编辑此对象': 'Edit Subject',
  '添加报告日志': 'Add Observation Log',
  '针对此观察目标尚未录入任何日志。': 'No reflection logs entered for this subject yet.',
  '去写观察日志': 'Create a log now',
  '点击查阅详情 →': 'Click to view details →',
  '编辑此研究对象': 'Edit Subject',
  '删除此研究对象': 'Delete Subject',
  '在数据之外，安放你的思考': 'A quiet space for contemplation beyond data',
  '选择观察样本：': 'Select observation sample:',
  '-- 请选择一个观察样本以开始书写 --': '-- Select a subject to begin writing --',
  '通用随笔': 'General Reflection',
  '在此处记下您的随笔，随写随存，可以随时在此删改...': 'Write your notes here, autosaved instantly...',
  '实时自动保存中 已写': 'Autosaved in real-time | Word count:',
  '字': 'words',
  '生成随笔备份节点': 'Generate Snap Backup',
  '生成当前存档点': 'Generate Archive Point',
  '随笔备份': 'Journal Backups',
  '您可以随时手动生成当前纸本的临时备份，并在大文本遭到误清空或误盖写时，一键安全回位。': 'Manually snapshot your current notebook anytime, and restore cleanly if you accidentally overwrite your text.',
  '恢复历史存档节点：': 'Restore Historical Archive:',
  '确定覆盖并历史回滚？': 'Restore and Overwrite?',
  '编辑观察日志': 'Edit Observation Log',
  '时间': 'Time',
  '立即保存': 'Save Now',
  '观察时间': 'Observation Time',
  '事实记录': 'Fact Record',
  '行为分类': 'Behavior Categorization',
  '第一时间反应': 'Immediate Reaction',
  '情绪反应': 'Emotional Response',
  '生理信号': 'Physical Signals',
  '即时反应': 'Immediate Action',
  '无记录': 'No record',
  '认知催化与演变': 'Cognitive Catalyst & Evolution',
  '演变转折点': 'Evolution Pivot Point',
  '运用的深度解构策略': 'Applied Deep Deconstruction Strategies',
  '生存法则与防同化自测': 'Survival Rule & Anti-assimilation Self-check',
  '生存法则': 'Survival Rule',
  '防同化自测': 'Anti-Assimilation Self-check',
  '辩证追问与自省': 'Dialectical Questioning & Self-reflection',
  '观察记录已保存': 'Observation report saved successfully.',
  '点击查看观察状态的区别与说明': 'Click to see status definitions and instructions',
  '确定': 'Confirm',
  '好的': 'OK',
  '恢复成功': 'Restore Successful',
  '历史备份已成功恢复并自动保存。': 'Historical backup has been restored and saved successfully.',
  '确定删除此存档点吗？': 'Are you sure you want to delete this archive point?',
  '删除成功': 'Delete Successful',
  '备份点已安全移除。': 'The backup point has been safely removed.',
  '等待开启书写': 'Waiting to start writing',
  '请选择上方需要追踪记录解构随笔的研究对象个体，本系统将为你自动调阅并智能开辟整块连贯白稿区。': 'Please select a research subject above to track and write reflections. The system will retrieve historical text and open a quiet writing area.',
  '暂无本研究员随笔档案的节点备份': 'No snapshot backups for this journal yet.',
  '管理/清理历史存档点：': 'Manage/Clean History Snapshots:',
  '备份点': 'Snapshot Point',
  '删除此存档点': 'Delete Backup Point',
  '全部研究对象': 'All Research Subjects',
  '日期范围': 'Date Range',
  '至': 'to',
  '关键词检索': 'Keyword Search',
  '检索事实或生存法则...': 'Search facts or survival rules...',
  '重置': 'Reset',
  '观察日志列表': 'Observation Log List',
  '筛选后共计': 'Filtered Total:',
  '没有匹配到符合筛选条件的实验观察日志。': 'No experimental observation logs matching the filter criteria were found.',
  '记录时间': 'Recorded At',
  ' [已完成]': ' [Completed]',
  '选择观察研究对象': 'Select Research Subject',
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('app_language');
      return (saved === 'en' || saved === 'zh') ? saved : 'zh';
    } catch {
      return 'zh';
    }
  });

  const changeLanguage = (newLang: Language) => {
    setLang(newLang);
    try {
      localStorage.setItem('app_language', newLang);
    } catch (e) {
      console.error('Error saving language:', e);
    }
  };

  const t = (text: string): string => {
    if (lang === 'zh') return text;
    if (!text) return '';
    
    // Support hashtags (e.g. #去人格化解读 -> #Depersonalization Stance)
    if (text.startsWith('#')) {
      const rest = text.slice(1);
      const translated = TRANSLATIONS[rest] || rest;
      return `#${translated}`;
    }

    // Strip possible whitespace/quotes
    const trimmed = text.trim();
    if (TRANSLATIONS[trimmed]) {
      return TRANSLATIONS[trimmed];
    }
    
    // Dynamic matching of quotes
    const cleanQuotes = trimmed.replace(/^“|”$/g, '');
    if (TRANSLATIONS[cleanQuotes]) {
      return `"${TRANSLATIONS[cleanQuotes]}"`;
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
